### ISSUE TITLE
init file n_compounds accepting floats as inputs

### ISSUE THREAD

**Issue by bryaniswright** [cmelab/planckton-flow#12]
the error that i encountered was that i set the number of compounds to be 1.0 which is a float and not an integer and planckton-flow was unable to read this value. the exact error is pasted below.

```
Using environment configuration: Bridges2Custom
ERROR: Encountered error during program execution: ''float' object cannot be interpreted as an integer'

Execute with '--show-traceback' or '--debug' to get more information.
Using environment configuration: Bridges2Custom
ERROR: Encountered error during program execution: 'Command 'singularity exec --nv $PLANCKTON_SIMG python /ocean/projects/dmr180028p/bwright/jobs/planckton-flow/src/project.py exec sample 91b70f61278b2dab1cd0dc3b43f1736a' returned non-zero exit status 1.'

Execute with '--show-traceback' or '--debug' to get more information.

```

**Comment by gwenwhite** [comment]
@jennyfothergill Would adding a docstring and/or hashed comment to the `init.py` file be a good fix?

**Comment by jennyfothergill** [comment]
@gwenwhite sorry I didn't see this sooner! Yes, a comment line is probably the best way to fix it. Alternatively we could cast any value entered in n_compounds to int. I prefer your suggestion though :)
